language: csharp
mono: none
dotnet: 2.1
script:
 - dotnet restore
 - dotnet build PlanningPoker.WebApi
 - dotnet build PlanningPoker.WebApi.Tests
 - dotnet build PlanningPoker.Entities
 - dotnet build PlanningPoker.Entities.Tests
 - dotnet build PlanningPoker.Shared
 - dotnet build PlanningPoker.Services
 - dotnet build PlanningPoker.Services.Tests
 # Will fail when running dotnet test, as it cant find tests in non-test project. See: https://github.com/Microsoft/vstest/issues/1129
 - dotnet vstest PlanningPoker.WebApi.Tests/bin/Debug/netcoreapp2.1/PlanningPoker.WebApi.Tests.dll
 - dotnet vstest PlanningPoker.Entities.Tests/bin/Debug/netcoreapp2.1/PlanningPoker.Entities.Tests.dll
 - dotnet vstest PlanningPoker.Services.Tests/bin/Debug/netcoreapp2.1/PlanningPoker.Services.Tests.dll
notifications:
  email: false
