language: csharp
mono: none
dotnet: 2.1
script:
 - dotnet restore
 - dotnet build
 # Will fail when running dotnet test, as it cant find tests in non-test project. See: https://github.com/Microsoft/vstest/issues/1129
 - dotnet vstest PlanningPoker.WebApi.Tests/bin/Debug/netcoreapp2.1/PlanningPoker.WebApi.Tests.dll