version: '3'

services:
  mssqql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@55w0rd"
      - "MSSQL_PID=Developer"