// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Pending>", Scope = "namespace", Target = "~N:PlanningPoker.App.ViewModels")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Pending>", Scope = "namespace", Target = "~N:PlanningPoker.App.ViewModels")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Pending>", Scope = "namespace", Target = "~N:PlanningPoker.App.Views.Session")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Pending>", Scope = "namespace", Target = "~N:PlanningPoker.App.Views.Session")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Pending>", Scope = "namespace", Target = "~N:PlanningPoker.App.Views.WelcomeScreen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Pending>", Scope = "namespace", Target = "~N:PlanningPoker.App.Views.WelcomeScreen")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~E:PlanningPoker.App.ViewModels.BaseViewModel.PropertyChanged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~E:PlanningPoker.App.ViewModels.RelayCommand.CanExecuteChanged")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.App._lazyProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.ViewModels.BaseViewModel.title")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.App.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.ItemsViewModel.#ctor")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters must be on same line or separate lines", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.BaseViewModel.SetProperty``1(``0@,``0,System.String,System.Action)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "<Pending>", Scope = "type", Target = "~T:PlanningPoker.App.ViewModels.BaseViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression must have justification", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.App.lazyProvider")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.ViewModels.JoinViewModel.nickname")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.ViewModels.JoinViewModel.repository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.JoinViewModel.#ctor(PlanningPoker.App.Models.ISessionRepository)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.LobbyViewModel.#ctor(PlanningPoker.App.Models.ISessionRepository)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~P:PlanningPoker.App.ViewModels.JoinViewModel.Nickname")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~P:PlanningPoker.App.ViewModels.LobbyViewModel.Title")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.Views.Session.Lobby.OnAppearing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~P:PlanningPoker.App.ViewModels.LobbyViewModel.Key")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~P:PlanningPoker.App.ViewModels.WelcomeViewModel.Nickname")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.ViewModels.JoinViewModel.client")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.ViewModels.WelcomeViewModel.client")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~F:PlanningPoker.App.ViewModels.WelcomeViewModel.nickname")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.JoinViewModel.#ctor(PlanningPoker.App.Models.ISessionClient)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.LobbyViewModel.#ctor(PlanningPoker.App.Models.ISessionClient)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.WelcomeViewModel.#ctor(Microsoft.Identity.Client.IPublicClientApplication,PlanningPoker.App.Models.ISettings,PlanningPoker.App.Models.ISessionClient)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.JoinCommand.#ctor(PlanningPoker.App.Models.ISessionClient,System.String,PlanningPoker.Shared.UserCreateDTO)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~M:PlanningPoker.App.ViewModels.SessionCreateViewModel.#ctor(PlanningPoker.App.Models.ISessionClient)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "<Pending>", Scope = "member", Target = "~P:PlanningPoker.App.ViewModels.SessionCreateViewModel.Title")]